version: "3.1"

language: ko

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy

assistant_id: 20250509-175341-genteel-solute
